app-folder: ${ZENITH_APP_FOLDER:./db}

logging:
  file:
    path: ${app-folder}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${app-folder}/h2.data;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    drop-first: false
    test-rollback-on-update: false

springdoc:
  api-docs:
    resolve-schema-properties: true
    path: /api
  swagger-ui:
    path: /api/doc
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true